
storeFile=../app/key.jks
storePassword=hdi365Project
keyPassword=hdi365Project
keyAlias=key
# storeFile=C://keys//hdi365_project//key.jks
# storeFile=//Users//raymondchan//Flutter files//keys//hdi365_project//key.jks

# to check SHA-256 fingerprints
# keytool -list -v -keystore android/app/key.jks       